# ==============================================================================
# Merged Lakeflow Source: open_meteo
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import logging
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/open_meteo/open_meteo_schemas.py
    ########################################################

    RETRIABLE_STATUS_CODES = {429, 500, 503}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry

    # ---------------------------------------------------------------------------
    # Metadata fields (present in every API response, injected into each row)
    # ---------------------------------------------------------------------------
    _METADATA_FIELDS = [
        StructField("latitude", DoubleType(), nullable=False),
        StructField("longitude", DoubleType(), nullable=False),
        StructField("elevation", DoubleType(), nullable=True),
        StructField("timezone", StringType(), nullable=True),
        StructField("timezone_abbreviation", StringType(), nullable=True),
        StructField("utc_offset_seconds", LongType(), nullable=True),
        StructField("generationtime_ms", DoubleType(), nullable=True),
    ]

    # ---------------------------------------------------------------------------
    # hourly_forecast schema
    # ---------------------------------------------------------------------------
    HOURLY_FORECAST_SCHEMA = StructType(
        _METADATA_FIELDS
        + [
            # time (primary key component)
            StructField("time", StringType(), nullable=False),
            # Core temperature & humidity
            StructField("temperature_2m", DoubleType(), nullable=True),
            StructField("relative_humidity_2m", LongType(), nullable=True),
            StructField("dew_point_2m", DoubleType(), nullable=True),
            StructField("apparent_temperature", DoubleType(), nullable=True),
            # Precipitation
            StructField("precipitation_probability", LongType(), nullable=True),
            StructField("precipitation", DoubleType(), nullable=True),
            StructField("rain", DoubleType(), nullable=True),
            StructField("showers", DoubleType(), nullable=True),
            StructField("snowfall", DoubleType(), nullable=True),
            StructField("snow_depth", DoubleType(), nullable=True),
            # Weather code
            StructField("weather_code", LongType(), nullable=True),
            # Pressure
            StructField("pressure_msl", DoubleType(), nullable=True),
            StructField("surface_pressure", DoubleType(), nullable=True),
            # Cloud cover
            StructField("cloud_cover", LongType(), nullable=True),
            StructField("cloud_cover_low", LongType(), nullable=True),
            StructField("cloud_cover_mid", LongType(), nullable=True),
            StructField("cloud_cover_high", LongType(), nullable=True),
            # Visibility
            StructField("visibility", DoubleType(), nullable=True),
            # Evapotranspiration
            StructField("evapotranspiration", DoubleType(), nullable=True),
            StructField("et0_fao_evapotranspiration", DoubleType(), nullable=True),
            StructField("vapour_pressure_deficit", DoubleType(), nullable=True),
            # Wind (10 m)
            StructField("wind_speed_10m", DoubleType(), nullable=True),
            StructField("wind_speed_80m", DoubleType(), nullable=True),
            StructField("wind_speed_120m", DoubleType(), nullable=True),
            StructField("wind_speed_180m", DoubleType(), nullable=True),
            StructField("wind_direction_10m", LongType(), nullable=True),
            StructField("wind_direction_80m", LongType(), nullable=True),
            StructField("wind_direction_120m", LongType(), nullable=True),
            StructField("wind_direction_180m", LongType(), nullable=True),
            StructField("wind_gusts_10m", DoubleType(), nullable=True),
            # Temperature at altitude
            StructField("temperature_80m", DoubleType(), nullable=True),
            StructField("temperature_120m", DoubleType(), nullable=True),
            StructField("temperature_180m", DoubleType(), nullable=True),
            # Soil
            StructField("soil_temperature_0cm", DoubleType(), nullable=True),
            StructField("soil_temperature_6cm", DoubleType(), nullable=True),
            StructField("soil_temperature_18cm", DoubleType(), nullable=True),
            StructField("soil_temperature_54cm", DoubleType(), nullable=True),
            StructField("soil_moisture_0_to_1cm", DoubleType(), nullable=True),
            StructField("soil_moisture_1_to_3cm", DoubleType(), nullable=True),
            StructField("soil_moisture_3_to_9cm", DoubleType(), nullable=True),
            StructField("soil_moisture_9_to_27cm", DoubleType(), nullable=True),
            StructField("soil_moisture_27_to_81cm", DoubleType(), nullable=True),
            # Surface & atmospheric stability
            StructField("surface_temperature", DoubleType(), nullable=True),
            StructField("cape", DoubleType(), nullable=True),
            StructField("lifted_index", DoubleType(), nullable=True),
            StructField("convective_inhibition", DoubleType(), nullable=True),
            StructField("freezing_level_height", DoubleType(), nullable=True),
            StructField("boundary_layer_height", DoubleType(), nullable=True),
            # Day/night
            StructField("is_day", LongType(), nullable=True),
            # Sunshine & radiation
            StructField("sunshine_duration", DoubleType(), nullable=True),
            StructField("shortwave_radiation", DoubleType(), nullable=True),
            StructField("direct_radiation", DoubleType(), nullable=True),
            StructField("diffuse_radiation", DoubleType(), nullable=True),
            StructField("direct_normal_irradiance", DoubleType(), nullable=True),
            StructField("global_tilted_irradiance", DoubleType(), nullable=True),
            StructField("terrestrial_radiation", DoubleType(), nullable=True),
            StructField("shortwave_radiation_instant", DoubleType(), nullable=True),
            StructField("direct_radiation_instant", DoubleType(), nullable=True),
            StructField("diffuse_radiation_instant", DoubleType(), nullable=True),
            StructField("direct_normal_irradiance_instant", DoubleType(), nullable=True),
            StructField("global_tilted_irradiance_instant", DoubleType(), nullable=True),
            StructField("terrestrial_radiation_instant", DoubleType(), nullable=True),
            # UV
            StructField("uv_index", DoubleType(), nullable=True),
            StructField("uv_index_clear_sky", DoubleType(), nullable=True),
            # Misc
            StructField("wet_bulb_temperature_2m", DoubleType(), nullable=True),
            StructField("lightning_potential", DoubleType(), nullable=True),
            StructField("total_column_integrated_water_vapour", DoubleType(), nullable=True),
            StructField("snowfall_height", DoubleType(), nullable=True),
        ]
    )

    # ---------------------------------------------------------------------------
    # daily_forecast schema
    # ---------------------------------------------------------------------------
    DAILY_FORECAST_SCHEMA = StructType(
        _METADATA_FIELDS
        + [
            # time (primary key component)
            StructField("time", StringType(), nullable=False),
            # Weather code
            StructField("weather_code", LongType(), nullable=True),
            # Temperature
            StructField("temperature_2m_max", DoubleType(), nullable=True),
            StructField("temperature_2m_min", DoubleType(), nullable=True),
            StructField("temperature_2m_mean", DoubleType(), nullable=True),
            StructField("apparent_temperature_max", DoubleType(), nullable=True),
            StructField("apparent_temperature_min", DoubleType(), nullable=True),
            StructField("apparent_temperature_mean", DoubleType(), nullable=True),
            # Sun
            StructField("sunrise", StringType(), nullable=True),
            StructField("sunset", StringType(), nullable=True),
            StructField("daylight_duration", DoubleType(), nullable=True),
            StructField("sunshine_duration", DoubleType(), nullable=True),
            # UV
            StructField("uv_index_max", DoubleType(), nullable=True),
            StructField("uv_index_clear_sky_max", DoubleType(), nullable=True),
            # Precipitation
            StructField("precipitation_sum", DoubleType(), nullable=True),
            StructField("rain_sum", DoubleType(), nullable=True),
            StructField("showers_sum", DoubleType(), nullable=True),
            StructField("snowfall_sum", DoubleType(), nullable=True),
            StructField("snowfall_water_equivalent_sum", DoubleType(), nullable=True),
            StructField("precipitation_hours", DoubleType(), nullable=True),
            StructField("precipitation_probability_max", LongType(), nullable=True),
            StructField("precipitation_probability_min", LongType(), nullable=True),
            StructField("precipitation_probability_mean", LongType(), nullable=True),
            # Wind
            StructField("wind_speed_10m_max", DoubleType(), nullable=True),
            StructField("wind_speed_10m_mean", DoubleType(), nullable=True),
            StructField("wind_speed_10m_min", DoubleType(), nullable=True),
            StructField("wind_gusts_10m_max", DoubleType(), nullable=True),
            StructField("wind_gusts_10m_mean", DoubleType(), nullable=True),
            StructField("wind_gusts_10m_min", DoubleType(), nullable=True),
            StructField("wind_direction_10m_dominant", LongType(), nullable=True),
            # Radiation
            StructField("shortwave_radiation_sum", DoubleType(), nullable=True),
            StructField("et0_fao_evapotranspiration", DoubleType(), nullable=True),
            # Dew point
            StructField("dew_point_2m_max", DoubleType(), nullable=True),
            StructField("dew_point_2m_min", DoubleType(), nullable=True),
            StructField("dew_point_2m_mean", DoubleType(), nullable=True),
            # Humidity
            StructField("relative_humidity_2m_max", LongType(), nullable=True),
            StructField("relative_humidity_2m_min", LongType(), nullable=True),
            StructField("relative_humidity_2m_mean", LongType(), nullable=True),
            # Pressure
            StructField("pressure_msl_max", DoubleType(), nullable=True),
            StructField("pressure_msl_min", DoubleType(), nullable=True),
            StructField("pressure_msl_mean", DoubleType(), nullable=True),
            StructField("surface_pressure_max", DoubleType(), nullable=True),
            StructField("surface_pressure_min", DoubleType(), nullable=True),
            StructField("surface_pressure_mean", DoubleType(), nullable=True),
            # Cloud cover
            StructField("cloud_cover_max", LongType(), nullable=True),
            StructField("cloud_cover_min", LongType(), nullable=True),
            StructField("cloud_cover_mean", LongType(), nullable=True),
            # Visibility
            StructField("visibility_max", DoubleType(), nullable=True),
            StructField("visibility_min", DoubleType(), nullable=True),
            StructField("visibility_mean", DoubleType(), nullable=True),
            # Vapour pressure deficit
            StructField("vapour_pressure_deficit_max", DoubleType(), nullable=True),
            # Wet bulb
            StructField("wet_bulb_temperature_2m_max", DoubleType(), nullable=True),
            StructField("wet_bulb_temperature_2m_min", DoubleType(), nullable=True),
            StructField("wet_bulb_temperature_2m_mean", DoubleType(), nullable=True),
            # CAPE
            StructField("cape_max", DoubleType(), nullable=True),
            StructField("cape_min", DoubleType(), nullable=True),
            StructField("cape_mean", DoubleType(), nullable=True),
            # Updraft
            StructField("updraft_max", DoubleType(), nullable=True),
        ]
    )

    # ---------------------------------------------------------------------------
    # Default variable subsets (sensible defaults when the user does not specify)
    # ---------------------------------------------------------------------------
    DEFAULT_HOURLY_VARIABLES = [
        "temperature_2m",
        "relative_humidity_2m",
        "dew_point_2m",
        "apparent_temperature",
        "precipitation_probability",
        "precipitation",
        "rain",
        "snowfall",
        "weather_code",
        "cloud_cover",
        "wind_speed_10m",
        "wind_direction_10m",
        "wind_gusts_10m",
        "visibility",
        "uv_index",
    ]

    DEFAULT_DAILY_VARIABLES = [
        "weather_code",
        "temperature_2m_max",
        "temperature_2m_min",
        "apparent_temperature_max",
        "apparent_temperature_min",
        "sunrise",
        "sunset",
        "precipitation_sum",
        "rain_sum",
        "snowfall_sum",
        "precipitation_probability_max",
        "wind_speed_10m_max",
        "wind_gusts_10m_max",
        "wind_direction_10m_dominant",
        "uv_index_max",
    ]


    ########################################################
    # src/databricks/labs/community_connector/sources/open_meteo/open_meteo.py
    ########################################################

    logger = logging.getLogger(__name__)

    _SUPPORTED_TABLES = ["hourly_forecast", "daily_forecast"]

    # Maps table name -> API response section key
    _TABLE_SECTION_MAP = {
        "hourly_forecast": "hourly",
        "daily_forecast": "daily",
    }


    class OpenMeteoLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the Open-Meteo Forecast API."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._latitude = options["latitude"]
            self._longitude = options["longitude"]
            self._apikey = options.get("apikey")

            if self._apikey:
                self._base_url = "https://customer-api.open-meteo.com/v1/forecast"
            else:
                self._base_url = "https://api.open-meteo.com/v1/forecast"

        # ------------------------------------------------------------------
        # HTTP helpers
        # ------------------------------------------------------------------

        def _request_with_retry(self, params: dict) -> requests.Response:
            """Issue a GET request to the Open-Meteo API with exponential-backoff retry."""
            backoff = INITIAL_BACKOFF
            resp = None
            for attempt in range(MAX_RETRIES):
                resp = requests.get(self._base_url, params=params, timeout=20)

                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp

                if attempt < MAX_RETRIES - 1:
                    logger.warning(
                        "Open-Meteo API returned %s on attempt %d/%d, retrying in %.1fs",
                        resp.status_code,
                        attempt + 1,
                        MAX_RETRIES,
                        backoff,
                    )
                    time.sleep(backoff)
                    backoff *= 2

            return resp  # type: ignore[return-value]

        # ------------------------------------------------------------------
        # LakeflowConnect interface
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            """Return the static list of supported tables."""
            return list(_SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """Return the full static schema for the requested table."""
            self._validate_table(table_name)
            if table_name == "hourly_forecast":
                return HOURLY_FORECAST_SCHEMA
            return DAILY_FORECAST_SCHEMA

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """Return snapshot metadata with composite primary keys."""
            self._validate_table(table_name)
            return {
                "primary_keys": ["latitude", "longitude", "time"],
                "ingestion_type": "snapshot",
            }

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Fetch forecast data and return row-oriented dicts.

            The Open-Meteo API returns parallel arrays; this method pivots them
            into one dict per timestep, injecting top-level metadata fields into
            each row.
            """
            self._validate_table(table_name)

            section_key = _TABLE_SECTION_MAP[table_name]

            # Determine which weather variables to request
            variables = self._resolve_variables(table_name, table_options)

            # Build query params
            params = self._build_params(section_key, variables, table_options)

            # Call the API
            resp = self._request_with_retry(params)

            if resp.status_code != 200:
                raise RuntimeError(
                    f"Open-Meteo API error (HTTP {resp.status_code}): {resp.text}"
                )

            body = resp.json()

            # The API returns {"error": true, "reason": "..."} on logical errors
            if body.get("error"):
                raise RuntimeError(f"Open-Meteo API error: {body.get('reason', body)}")

            section_data = body.get(section_key, {})
            rows = self._pivot_to_rows(body, section_data, variables)

            return iter(rows), {}

        # ------------------------------------------------------------------
        # Internal helpers
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in _SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {_SUPPORTED_TABLES}"
                )

        def _resolve_variables(
            self, table_name: str, table_options: dict[str, str]
        ) -> list[str]:
            """Determine the list of weather variables to request.

            Users can override via ``hourly_variables`` or ``daily_variables`` in
            table_options (comma-separated).  Falls back to the default list.
            """
            if table_name == "hourly_forecast":
                opt_key = "hourly_variables"
                defaults = DEFAULT_HOURLY_VARIABLES
            else:
                opt_key = "daily_variables"
                defaults = DEFAULT_DAILY_VARIABLES

            raw = table_options.get(opt_key, "")
            if raw.strip():
                return [v.strip() for v in raw.split(",") if v.strip()]
            return list(defaults)

        def _build_params(
            self,
            section_key: str,
            variables: list[str],
            table_options: dict[str, str],
        ) -> dict:
            """Assemble query parameters for the API request."""
            params: dict[str, str] = {
                "latitude": self._latitude,
                "longitude": self._longitude,
                section_key: ",".join(variables),
            }

            # Optional parameters forwarded from table_options
            for opt_key in (
                "forecast_days",
                "timezone",
                "temperature_unit",
                "wind_speed_unit",
                "precipitation_unit",
                "models",
            ):
                value = table_options.get(opt_key, "")
                if value.strip():
                    params[opt_key] = value.strip()

            # API key (from connection options)
            if self._apikey:
                params["apikey"] = self._apikey

            return params

        def _pivot_to_rows(
            self,
            body: dict,
            section_data: dict,
            variables: list[str],
        ) -> list[dict]:
            """Convert the parallel-array response into row-oriented dicts.

            Each row includes the top-level metadata fields plus one timestep's
            values for all requested variables.
            """
            time_values = section_data.get("time", [])
            if not time_values:
                return []

            # Extract top-level metadata once
            metadata = {
                "latitude": body.get("latitude"),
                "longitude": body.get("longitude"),
                "elevation": body.get("elevation"),
                "timezone": body.get("timezone"),
                "timezone_abbreviation": body.get("timezone_abbreviation"),
                "utc_offset_seconds": body.get("utc_offset_seconds"),
                "generationtime_ms": body.get("generationtime_ms"),
            }

            num_rows = len(time_values)
            rows: list[dict] = []

            for i in range(num_rows):
                row = dict(metadata)
                row["time"] = time_values[i]
                for var in variables:
                    values = section_data.get(var)
                    if values is not None and i < len(values):
                        row[var] = values[i]
                    else:
                        row[var] = None
                rows.append(row)

            return rows


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = OpenMeteoLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
